"""initial migration

Revision ID: 88a71d4f86e7
Revises: bfe4b89d1390
Create Date: 2024-07-19 17:40:08.315068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a71d4f86e7'
down_revision: Union[str, None] = 'bfe4b89d1390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_table('nba_standings',
    sa.Column('winnings_percentage', sa.Float(), nullable=True),
    sa.Column('games_back', sa.String(), nullable=True),
    sa.Column('points_percentage_game', sa.Float(), nullable=True),
    sa.Column('opp_points_percentage_game', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nba_standings_id'), 'nba_standings', ['id'], unique=False)
    op.create_table('nba_teams',
    sa.Column('team_logo', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nba_teams_id'), 'nba_teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nba_teams_id'), table_name='nba_teams')
    op.drop_table('nba_teams')
    op.drop_index(op.f('ix_nba_standings_id'), table_name='nba_standings')
    op.drop_table('nba_standings')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
